const PRESET_STYLES = {
  tiktok: {
    fontName: "Anton",
    fontWeight: 900,
    outlineWidth: 3,
    outlineColor: "#000000",
    shadowDepth: 0,
    shadowColor: "transparent",
    textColor: "#FFFFFF",
    highlightColor: "#FE2C55",
    highlightScale: 1.0,
    highlightGlow: false,
    highlightGlowColor: "#FE2C55",
    highlightGlowIntensity: 0,
    highlightBg: null,
    highlightRadius: 0,
    animIn: 0,
    animOut: 0,
    animType: "instant",
    verticalPct: 55,
  },
  popup: {
    fontName: "Anton",
    fontWeight: 900,
    outlineWidth: 5,
    outlineColor: "#000000",
    shadowDepth: 3,
    shadowColor: "rgba(0,0,0,0.5)",
    textColor: "#FFFFFF",
    highlightColor: "#FFD400",
    highlightScale: 1.15,
    highlightGlow: true,
    highlightGlowColor: "#FFD400",
    highlightGlowIntensity: 5,
    highlightBg: null,
    highlightRadius: 0,
    animIn: 80,
    animOut: 60,
    animType: "bounce",
    verticalPct: 55,
  },
  bounce: {
    fontName: "Montserrat",
    fontWeight: 800,
    outlineWidth: 4,
    outlineColor: "#000000",
    shadowDepth: 8,
    shadowColor: "rgba(0,0,0,0.6)",
    textColor: "#FFFFFF",
    highlightColor: "#FFD700",
    highlightScale: 1.25,
    highlightGlow: true,
    highlightGlowColor: "#FFD700",
    highlightGlowIntensity: 6,
    highlightBg: null,
    highlightRadius: 0,
    animIn: 150,
    animOut: 100,
    animType: "bounce",
    verticalPct: 28,
  },
  highlight: {
    fontName: "Poppins",
    fontWeight: 700,
    outlineWidth: 0,
    outlineColor: "transparent",
    shadowDepth: 2,
    shadowColor: "rgba(0,0,0,0.3)",
    textColor: "#FFFFFF",
    highlightColor: "#FFFFFF",
    highlightScale: 1.0,
    highlightGlow: false,
    highlightGlowColor: "#00D4FF",
    highlightGlowIntensity: 0,
    highlightBg: "#5b3eff",
    highlightRadius: 8,
    animIn: 80,
    animOut: 60,
    animType: "fade",
    verticalPct: 26,
  },
  karaoke: {
    fontName: "Bebas Neue",
    fontWeight: 400,
    outlineWidth: 2,
    outlineColor: "#000000",
    shadowDepth: 2,
    shadowColor: "rgba(0,0,0,0.4)",
    textColor: "rgba(255,255,255,0.45)",
    highlightColor: "#FFEB3B",
    highlightScale: 1.0,
    highlightGlow: false,
    highlightGlowColor: "#FFEB3B",
    highlightGlowIntensity: 0,
    highlightBg: null,
    highlightRadius: 0,
    animIn: 0,
    animOut: 0,
    animType: "instant",
    verticalPct: 26,
  },
  classic: {
    fontName: "Inter",
    fontWeight: 600,
    outlineWidth: 2,
    outlineColor: "#000000",
    shadowDepth: 3,
    shadowColor: "rgba(0,0,0,0.5)",
    textColor: "#FFFFFF",
    highlightColor: "#4FC3F7",
    highlightScale: 1.05,
    highlightGlow: false,
    highlightGlowColor: "#4FC3F7",
    highlightGlowIntensity: 3,
    highlightBg: null,
    highlightRadius: 0,
    animIn: 100,
    animOut: 80,
    animType: "fade",
    verticalPct: 26,
  },
  minimal: {
    fontName: "Inter",
    fontWeight: 300,
    outlineWidth: 0,
    outlineColor: "transparent",
    shadowDepth: 0,
    shadowColor: "transparent",
    textColor: "#FFFFFF",
    highlightColor: "#FFFFFF",
    highlightScale: 1.0,
    highlightGlow: false,
    highlightGlowColor: "#FFFFFF",
    highlightGlowIntensity: 0,
    highlightBg: null,
    highlightRadius: 0,
    animIn: 0,
    animOut: 0,
    animType: "instant",
    verticalPct: 26,
  },
};

const PRESET_LIST = [
  { value: "popup", label: "Pop-Up", icon: "Pu" },
  { value: "tiktok", label: "TikTok", icon: "T" },
  { value: "bounce", label: "Bounce", icon: "Bn" },
  { value: "highlight", label: "Highlight", icon: "H" },
  { value: "karaoke", label: "Karaoke", icon: "K" },
  { value: "classic", label: "Classic", icon: "C" },
  { value: "minimal", label: "Minimal", icon: "M" },
];

export function getCaptionPresetStyle(preset, userConfig) {
  const presetStyle = PRESET_STYLES[preset] || PRESET_STYLES.classic;
  const merged = { ...presetStyle };

  if (userConfig) {
    const presetKeys = Object.keys(presetStyle);
    for (const key of Object.keys(userConfig)) {
      if (presetKeys.indexOf(key) === -1 || userConfig[key] !== undefined && userConfig[key] !== presetStyle[key]) {
        merged[key] = userConfig[key];
      }
    }
  }

  return merged;
}

export { PRESET_STYLES, PRESET_LIST };
