export const PLANS = {
  free: {
    id: "free",
    name: "Free",
    price: 0,
    monthlyCredits: 100,
    description: "Try Velora with no commitment",
    recommendedUser: "Exploring",
    badge: null,
    estimatedClips: "~5 clips/mo",
    features: [
      { text: "Basic AI clipping", included: true },
      { text: "720p export", included: true },
      { text: "Watermark-free", included: false },
      { text: "Standard captions", included: true },
      { text: "Pop-Up Captions", included: false },
      { text: "1 active project", included: true },
      { text: "Community support", included: true },
      { text: "Basic video stabilization", included: true },
      { text: "Basic face tracking", included: true },
    ],
    comparison: {
      credits: "100/mo",
      watermarkRemoval: false,
      exportQuality: "720p",
      aiClipping: "Basic",
      customClipDuration: false,
      customClipCount: false,
      premiumCaptions: false,
      animatedCaptions: false,
      popUpCaptions: false,
      brandKit: false,
      savedTemplates: false,
      activeProjects: "1",
      storage: "—",
      batchProcessing: false,
      teamMembers: "—",
      apiAccess: false,
      processingPriority: "Standard",
      supportLevel: "Community",
      videoStabilization: "Basic",
      aiFaceTracking: "Basic",
      smartAutoReframe: false,
      closeUpFraming: false,
      autoPunchIn: false,
      captionPresets: "3",
    },
  },
  starter: {
    id: "starter",
    name: "Starter",
    price: 5,
    monthlyCredits: 1000,
    description: "For casual creators getting started",
    recommendedUser: "Casual Creators",
    badge: null,
    estimatedClips: "~50 clips/mo",
    features: [
      { text: "Basic AI clipping", included: true },
      { text: "1080p export", included: true },
      { text: "Watermark-free", included: true },
      { text: "Standard captions", included: true },
      { text: "3 active projects", included: true },
      { text: "1 GB storage", included: true },
      { text: "Premium captions", included: false },
      { text: "Pop-Up Captions", included: false },
      { text: "Brand Kit", included: false },
      { text: "Saved Templates", included: false },
      { text: "Batch Processing", included: false },
      { text: "Email support", included: true },
      { text: "Improved stabilization", included: true },
      { text: "Basic face tracking", included: true },
    ],
    comparison: {
      credits: "1,000/mo",
      watermarkRemoval: true,
      exportQuality: "1080p",
      aiClipping: "Standard",
      customClipDuration: false,
      customClipCount: false,
      premiumCaptions: false,
      animatedCaptions: false,
      popUpCaptions: false,
      brandKit: false,
      savedTemplates: false,
      activeProjects: "3",
      storage: "1 GB",
      batchProcessing: false,
      teamMembers: "—",
      apiAccess: false,
      processingPriority: "Standard",
      supportLevel: "Email",
      videoStabilization: "Improved",
      aiFaceTracking: "Basic",
      smartAutoReframe: false,
      closeUpFraming: false,
      autoPunchIn: false,
      captionPresets: "3",
    },
  },
  creator: {
    id: "creator",
    name: "Creator",
    price: 12,
    monthlyCredits: 5000,
    description: "Built for content creators who post regularly",
    recommendedUser: "Content Creators",
    badge: "Most Popular",
    estimatedClips: "~250 clips/mo",
    features: [
      { text: "Advanced AI clipping", included: true },
      { text: "1080p export", included: true },
      { text: "Watermark-free", included: true },
      { text: "Premium captions", included: true },
      { text: "Animated captions", included: false },
      { text: "Pop-Up Captions", included: false },
      { text: "Custom clip duration", included: true },
      { text: "Custom clip count", included: true },
      { text: "Brand Kit", included: true },
      { text: "Saved Templates", included: true },
      { text: "10 active projects", included: true },
      { text: "10 GB storage", included: true },
      { text: "Batch Processing", included: false },
      { text: "Team Members", included: false },
      { text: "API Access", included: false },
      { text: "Priority processing", included: true },
      { text: "Priority support", included: true },
      { text: "Advanced stabilization", included: true },
      { text: "Advanced face tracking", included: true },
      { text: "Smart auto-reframe", included: true },
    ],
    comparison: {
      credits: "5,000/mo",
      watermarkRemoval: true,
      exportQuality: "1080p",
      aiClipping: "Advanced",
      customClipDuration: true,
      customClipCount: true,
      premiumCaptions: true,
      animatedCaptions: false,
      popUpCaptions: false,
      brandKit: true,
      savedTemplates: true,
      activeProjects: "10",
      storage: "10 GB",
      batchProcessing: false,
      teamMembers: "—",
      apiAccess: false,
      processingPriority: "Fast",
      supportLevel: "Priority",
      videoStabilization: "Advanced",
      aiFaceTracking: "Advanced",
      smartAutoReframe: "Basic",
      closeUpFraming: false,
      autoPunchIn: false,
      captionPresets: "3",
    },
  },
  pro: {
    id: "pro",
    name: "Pro",
    price: 29,
    monthlyCredits: 15000,
    description: "For professionals who need serious volume",
    recommendedUser: "Professionals",
    badge: "For Professionals",
    estimatedClips: "~750 clips/mo",
    features: [
      { text: "Advanced AI clipping", included: true },
      { text: "4K export", included: true },
      { text: "Watermark-free", included: true },
      { text: "Premium captions", included: true },
      { text: "Animated captions", included: true },
      { text: "Pop-Up Captions", included: true },
      { text: "Custom clip duration", included: true },
      { text: "Custom clip count", included: true },
      { text: "Brand Kit", included: true },
      { text: "Saved Templates", included: true },
      { text: "50 active projects", included: true },
      { text: "50 GB storage", included: true },
      { text: "Batch Processing", included: true },
      { text: "Team Members", included: "3" },
      { text: "API Access", included: false },
      { text: "Priority processing", included: true },
      { text: "Priority support", included: true },
      { text: "Premium stabilization", included: true },
      { text: "Premium face tracking", included: true },
      { text: "Smart auto-reframe", included: true },
      { text: "AI Close-Up Framing", included: true },
      { text: "Auto Punch-In", included: true },
      { text: "6 Caption Presets", included: true },
    ],
    comparison: {
      credits: "15,000/mo",
      watermarkRemoval: true,
      exportQuality: "4K",
      aiClipping: "Advanced",
      customClipDuration: true,
      customClipCount: true,
      premiumCaptions: true,
      animatedCaptions: true,
      popUpCaptions: true,
      brandKit: true,
      savedTemplates: true,
      activeProjects: "50",
      storage: "50 GB",
      batchProcessing: true,
      teamMembers: "3",
      apiAccess: false,
      processingPriority: "Fast",
      supportLevel: "Priority",
      videoStabilization: "Premium",
      aiFaceTracking: "Premium",
      smartAutoReframe: "Advanced",
      closeUpFraming: "Advanced",
      autoPunchIn: true,
      captionPresets: "6",
    },
  },
  business: {
    id: "business",
    name: "Business",
    price: 79,
    monthlyCredits: 50000,
    description: "For teams and agencies at scale",
    recommendedUser: "Teams & Agencies",
    badge: "For Teams",
    estimatedClips: "~2,500 clips/mo",
    features: [
      { text: "Advanced AI clipping", included: true },
      { text: "4K export", included: true },
      { text: "Watermark-free", included: true },
      { text: "Premium captions", included: true },
      { text: "Animated captions", included: true },
      { text: "Pop-Up Captions", included: true },
      { text: "Custom clip duration", included: true },
      { text: "Custom clip count", included: true },
      { text: "Brand Kit", included: true },
      { text: "Saved Templates", included: true },
      { text: "Unlimited projects", included: true },
      { text: "500 GB storage", included: true },
      { text: "Batch Processing", included: true },
      { text: "Team Members", included: "10" },
      { text: "API Access", included: true },
      { text: "Fastest processing", included: true },
      { text: "Dedicated support", included: true },
      { text: "All video enhancements", included: true },
      { text: "AI Close-Up Framing", included: true },
      { text: "Auto Punch-In", included: true },
      { text: "6 Caption Presets", included: true },
      { text: "Team video processing", included: true },
    ],
    comparison: {
      credits: "50,000/mo",
      watermarkRemoval: true,
      exportQuality: "4K",
      aiClipping: "Advanced",
      customClipDuration: true,
      customClipCount: true,
      premiumCaptions: true,
      animatedCaptions: true,
      popUpCaptions: true,
      brandKit: true,
      savedTemplates: true,
      activeProjects: "Unlimited",
      storage: "500 GB",
      batchProcessing: true,
      teamMembers: "10",
      apiAccess: true,
      processingPriority: "Fastest",
      supportLevel: "Dedicated",
      videoStabilization: "Premium",
      aiFaceTracking: "Premium",
      smartAutoReframe: "Premium",
      closeUpFraming: "Premium",
      autoPunchIn: true,
      captionPresets: "6",
    },
  },
};

export const ENTERPRISE_PLAN = {
  id: "enterprise",
  name: "Enterprise",
  price: null,
  monthlyCredits: null,
  description: "Custom pricing for large organizations",
  recommendedUser: "Large Organizations",
  badge: null,
  estimatedClips: "Custom",
  features: [
    { text: "Everything in Business", included: true },
    { text: "Custom credit allocations", included: true },
    { text: "Dedicated account manager", included: true },
    { text: "SLA guarantee", included: true },
    { text: "Custom integrations", included: true },
    { text: "On-premise deployment", included: true },
  ],
};

export const PLAN_ORDER = ["free", "starter", "creator", "pro", "business"];

export const CREDIT_PACKS = [
  { id: "pack_starter", name: "Starter Pack", credits: 1000, price: 5, perCredit: "0.5¢/cr", badge: null },
  { id: "pack_creator", name: "Creator Pack", credits: 5000, price: 20, perCredit: "0.4¢/cr", badge: "Best Value" },
  { id: "pack_pro", name: "Pro Pack", credits: 15000, price: 50, perCredit: "0.33¢/cr", badge: null },
  { id: "pack_business", name: "Business Pack", credits: 50000, price: 150, perCredit: "0.3¢/cr", badge: null },
];

export const COMPARISON_ROWS = [
  { key: "credits", label: "Monthly Credits" },
  { key: "watermarkRemoval", label: "Watermark Removal" },
  { key: "exportQuality", label: "Export Quality" },
  { key: "aiClipping", label: "AI Clipping" },
  { key: "customClipDuration", label: "Custom Clip Duration" },
  { key: "customClipCount", label: "Custom Clip Count" },
  { key: "premiumCaptions", label: "Premium Captions" },
  { key: "animatedCaptions", label: "Animated Captions" },
  { key: "popUpCaptions", label: "Pop-Up Captions" },
  { key: "brandKit", label: "Brand Kit" },
  { key: "savedTemplates", label: "Saved Templates" },
  { key: "activeProjects", label: "Active Projects" },
  { key: "storage", label: "Storage" },
  { key: "batchProcessing", label: "Batch Processing" },
  { key: "teamMembers", label: "Team Members" },
  { key: "apiAccess", label: "API Access" },
  { key: "processingPriority", label: "Processing Priority" },
  { key: "supportLevel", label: "Support Level" },
  { key: "videoStabilization", label: "Video Stabilization" },
  { key: "aiFaceTracking", label: "AI Face Tracking" },
  { key: "smartAutoReframe", label: "Smart Auto-Reframe" },
  { key: "closeUpFraming", label: "AI Close-Up Framing" },
  { key: "autoPunchIn", label: "Auto Punch-In" },
  { key: "captionPresets", label: "Caption Presets" },
];

export const FAQS = [
  {
    q: "Do unused subscription credits roll over?",
    a: "Subscription credits reset every billing cycle. Unused subscription credits expire at renewal. Credit pack purchases never expire and carry forward indefinitely.",
  },
  {
    q: "How do subscription credits and credit packs work together?",
    a: "When spending credits, subscription credits are used first. Once your subscription credits reach zero, Velora automatically begins consuming your purchased credit pack credits.",
  },
  {
    q: "Can I get a refund?",
    a: "We offer refunds within 7 days of purchase if you haven't used any credits from that transaction. Contact support and we'll process it promptly.",
  },
  {
    q: "What happens when I run out?",
    a: "You can still browse your dashboard, but clip generation will be paused. Purchase a credit pack or upgrade your plan to continue generating clips.",
  },
  {
    q: "How do I cancel my subscription?",
    a: "Open the Billing Portal from the Manage Subscription section. You can cancel anytime — your plan stays active until the end of the current billing period.",
  },
  {
    q: "Can I change plans?",
    a: "Yes. Upgrade or downgrade anytime from the pricing section. Changes take effect immediately and credits are prorated.",
  },
];

export function getRecommendedPlan(estimatedCredits) {
  for (const planId of PLAN_ORDER) {
    if (estimatedCredits <= PLANS[planId].monthlyCredits) return planId;
  }
  return "business";
}

export function getPlanCredits(plan) {
  return PLANS[plan]?.monthlyCredits ?? PLANS.free.monthlyCredits;
}
